#!/bin/bash
rm tags/*.html tags/*.xml
scalac -classpath snakeyaml-1.7.jar gentags.scala
scala -classpath snakeyaml-1.7.jar:. gentags
git add --all tags/*.html tags/*.xml
git commit tags/*.html tags/*.xml -m "Automatic commit of autogenerated tag pages."
